### ISSUE TITLE
Error raised when matching IO.gets

### ISSUE THREAD

**Issue by danascheider** [jjh42/mock#49]
I am writing a test and need to mock `IO.gets`. The function I am testing is not written yet, so the test is expected to fail. However, it is currently raising an ugly error instead. This is the error text:
```
16:20:09.868 [error] GenEvent handler ExUnit.CLIFormatter installed in #PID<0.152.0> terminating
** (UndefinedFunctionError) function IO.chardata_to_string/1 is undefined (module IO is not available)
    (elixir) IO.chardata_to_string('/Users/dana/Development/gherkin-elixir-sandbox')
    (elixir) lib/path.ex:313: Path.relative_to_cwd/1
    (ex_unit) lib/ex_unit/formatter.ex:292: ExUnit.Formatter.with_location/1
    (ex_unit) lib/ex_unit/formatter.ex:112: ExUnit.Formatter.format_test_failure/5
    (ex_unit) lib/ex_unit/cli_formatter.ex:71: ExUnit.CLIFormatter.handle_event/2
    (stdlib) gen_event.erl:533: :gen_event.server_update/4
    (stdlib) gen_event.erl:515: :gen_event.server_notify/4
    (stdlib) gen_event.erl:256: :gen_event.handle_msg/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {:test_finished, %ExUnit.Test{case: GherkinTokenScannerTest, logs: "", name: :"test .read\\2 returns a token when line can be read from IO", state: {:failed, [{:error, %ErlangError{original: {:undefined_function, {IO, :gets, 0}}}, [{:meck, :check_expect_result, 1, [file: 'src/meck.erl', line: 670]}, {Mock, :_install_mock, 2, [file: 'lib/mock.ex', line: 127]}, {GherkinTokenScannerTest, :"test .read\\2 returns a token when line can be read from IO", 1, [file: 'test/token_scanner_test.exs', line: 17]}]}]}, tags: %{async: false, case: GherkinTokenScannerTest, describe: nil, file: "/Users/dana/Development/gherkin-elixir-sandbox/test/token_scanner_test.exs", line: 11, registered: %{}, test: :"test .read\\2 returns a token when line can be read from IO", type: :test}, time: 68324}}
State: %{colors: [enabled: true], failures_counter: 0, invalids_counter: 0, seed: 180995, skipped_counter: 0, tests_counter: %{test: 43}, trace: false, width: 80}
```

My test file is as follows:
```elixir
defmodule GherkinTokenScannerTest do
  use ExUnit.Case, async: false
  doctest Gherkin.TokenScanner

  import Mock

  test ".read\\2 returns a token when line can be read from IO" do
    expected_output = %Gherkin.Token{
      line: %Gherkin.GherkinLine{text: "Feature: Hello world", line_number: 2},
      location: %{line: 2}
    }

    with_mock IO, [gets: fn() -> "Feature: Hello world" end] do
      assert Gherkin.TokenScanner.read(:stdin, 1) == expected_output
    end
  end
end
```
And my module code looks like this:
```elixir
defmodule Gherkin.TokenScanner do
  def read(io, line_number \\ 0) do
  end
end
```
This is probably just me screwing something up, but if you could point me in the right direction, that would be much appreciated.

Thanks!

**Comment by jjh42** [comment]
You are never importing the IO module before you try and mock it?

**Comment by danascheider** [comment]
That must be it, I didn't realize the IO module needed to be imported.
