### ISSUE TITLE
Problem with fetch package mock on Windows

### ISSUE THREAD

**Issue by waldest** [jjh42/mock#86]
When I try to call 

`mix deps.get`

I can't install dependency and I see an error:
`
Running dependency resolution...                                    
Dependency resolution completed:                                    
  meck 0.8.10                                                       
  mock 0.3.1                                                        
* Updating mock (Hex package)                                       
  Checking package (https://repo.hex.pm/tarballs/mock-0.3.1.tar)    
  Fetched package                                                   
** (exit) an exception was raised:                                  
    ** (CaseClauseError) no case clause matching: {:error, :einval} 
        (stdlib) erl_tar.erl:598: :erl_tar.extract1/4               
        (stdlib) erl_tar.erl:571: :erl_tar.foldl_read1/4            
        (stdlib) erl_tar.erl:554: :erl_tar.foldl_read0/4            
        (stdlib) erl_tar.erl:546: :erl_tar.foldl_read/4             
        (hex) lib/hex/tar.ex:94: Hex.Tar.extract_contents/3         
        (hex) lib/hex/tar.ex:43: Hex.Tar.unpack/3                   
        (hex) lib/hex/scm.ex:110: Hex.SCM.checkout/1                
        (mix) lib/mix/dep/fetcher.ex:61: Mix.Dep.Fetcher.do_fetch/3 
    (stdlib) erl_tar.erl:556: :erl_tar.foldl_read0/4                
    (stdlib) erl_tar.erl:546: :erl_tar.foldl_read/4                 
    (hex) lib/hex/tar.ex:94: Hex.Tar.extract_contents/3             
    (hex) lib/hex/tar.ex:43: Hex.Tar.unpack/3                       
    (hex) lib/hex/scm.ex:110: Hex.SCM.checkout/1                    
    (mix) lib/mix/dep/fetcher.ex:61: Mix.Dep.Fetcher.do_fetch/3     
    (mix) lib/mix/dep/converger.ex:177: Mix.Dep.Converger.all/9     
    (mix) lib/mix/dep/converger.ex:186: Mix.Dep.Converger.all/9
`

**Comment by Olshansk** [comment]
Did you ever resolve this issue?

**Comment by eteeselink** [comment]
FWIW I'm on Windows too and I did not have this problem.
